import styles from "../styles/Scroll.module.css";

export default ( ) => {
  return (<>
  <div className={styles.scroller}><p>1 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>2 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>4 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>5 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>6 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>7 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>8 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>9 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>10 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>11 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>12 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>13 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>14 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>15 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>16 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>17 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>18 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>19 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>20 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>21 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>22 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>23 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  <p>24 Lorem ipsum later dubt seu sdfslf jddy rstghsf trhrs iofg nmd grge ety er ye e yety e ye y eryeryerlkjterk gereryeybjey eykeynekj eyjke jre rkjtyktjy thjy ty tyh y rtyjrtkjmekjyty tyetjy tjhy tj rtyjtnymtybtyj rtnmy jgl;etjoiruyie my sisrkt yrsy hjsyis5yk 5yk54ywiy n usfakfei shguakdgiu jalkffjjklaj aflkyeibfhab raaaaaajnvaa ru a rhakjfnkjarbg aerrhgjakka</p>
  </div>
  </>)
}